%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Haijie Zuo\Documents\meep\strip-wvg-bands.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/01/17 11:48:30

%% Initialize variables.
filename = 'C:\Users\Haijie Zuo\Documents\meep\strip-wvg-bands.dat';
delimiter = ',';
endRow = 22;

%% Format for each line of text:
%   column2: double (%f)
%	column3: double (%f)
%   column4: double (%f)
%	column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow, 'Delimiter', delimiter, 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
stripwvgbands = table(dataArray{1:end-1}, 'VariableNames', {'VarName2','VarName3','VarName4','VarName5'});

%% Clear temporary variables
clearvars filename delimiter endRow formatSpec fileID dataArray ans;